name: Build Minecraft Mod

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'

    - name: Gradle build
      run: ./gradlew build

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: minecraft-mod
        path: build/libs/*.jar
