name: Build Minecraft Mod

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'

    - name: Setup Gradle
      uses: gradle/wrapper-validation-action@v1 # Правильное действие для настройки Gradle

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: minecraft-mod
        path: build/libs/*.jar
