name: Build Minecraft Mod

on:
  push:
    branches:
      - main  # или master, если твоя основная ветка называется так
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Права для работы с содержимым репозитория
      packages: write  # Если планируешь публиковать в пакеты, оставь эту строку

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'  # Для Minecraft 1.7.10 требуется Java 8

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v2

    - name: Build with Gradle
      run: ./gradlew build  # Запуск сборки мода через Gradle

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: minecraft-mod
        path: build/libs/*.jar  # Путь к собранному .jar файлу мода
