name: Gradle Publish

on:
  push:
    tags:
      - 'v*'  # Публикация будет происходить при создании тега, например, v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'

    - name: Setup Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ secrets.GITHUB_ACTOR }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
